apiVersion: v1
kind: Service
metadata:
  name: gradeboost-{{ default "staging" .Release.Namespace }}-nginx
  labels:
    tier: backend
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 4200
  selector:
    app: gradeboost-{{ default "staging" .Release.Namespace }}-nginx
    tier: backend