apiVersion: v1
kind: Service
metadata:
  name: gradeboost-{{ default "staging" .Release.Namespace }}-nginx
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 4200
    protocol: TCP
  selector:
    app: gradeboost-{{ default "staging" .Release.Namespace }}