apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gradeboost-{{ default "staging" .Release.Namespace }}-ingress
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - gradeboost{{ if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}.cs{{- end}}.{{ .Values.dns.name }}
    secretName: tls-secret-gradeboost-{{ default "staging" .Release.Namespace }}
  rules:
  - host: gradeboost{{ if ne .Release.Namespace "production" }}-{{ default "staging" .Release.Namespace }}.cs{{- end}}.{{ .Values.dns.name }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: gradeboost-{{ default "staging" .Release.Namespace }}-nginx
            port:
              number: 4200
